import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import HomeLayout from "@components/layouts/HomeLayout"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
   title: "Instagram",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <html lang='en'>
         <body className={inter.className}>
            <HomeLayout>{children}</HomeLayout>
         </body>
      </html>
   )
}
